[package]
edition = "2018"
name = "zzz"
version = "0.1.0"

[dependencies]
confy = "0.4.0"
eframe = "0.15.0"
reqwest = { version = "0.11.6", features = ["blocking", "json"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.1"

